REM INSERTING into CSADMIN.TBL_FACULTY_TYPE
SET DEFINE OFF;
Insert into CSADMIN.TBL_FACULTY_TYPE (FACULTY_TYPE) values ('Collaborator');
Insert into CSADMIN.TBL_FACULTY_TYPE (FACULTY_TYPE) values ('Primary');
