REM INSERTING into CSADMIN.TBL_USERS
SET DEFINE OFF;
Insert into CSADMIN.TBL_USERS (USER_ID,LAST_NAME,FIRST_NAME,TITLE,PHONE,EMAIL,EMPLID) values ('FRIELJ','Friel','Jeffrey','Faculty','5738829464','frielj@missouri.edu','12345678');
Insert into CSADMIN.TBL_USERS (USER_ID,LAST_NAME,FIRST_NAME,TITLE,PHONE,EMAIL,EMPLID) values ('TIGERT','Tiger','Truman','Course Coordinator','5738829464','tigert@missouri.edu','23456789');
