REM INSERTING into CSADMIN.TBL_INSTITUTION
SET DEFINE OFF;
Insert into CSADMIN.TBL_INSTITUTION (INSTITUTION,INSTIT_DESCR) values ('COLUM','Columbia');
Insert into CSADMIN.TBL_INSTITUTION (INSTITUTION,INSTIT_DESCR) values ('UMKC','Kansas City');
Insert into CSADMIN.TBL_INSTITUTION (INSTITUTION,INSTIT_DESCR) values ('UMSL','St. Louis');
Insert into CSADMIN.TBL_INSTITUTION (INSTITUTION,INSTIT_DESCR) values ('ROLLA','Rolla');
commit;
