REM INSERTING into CSADMIN.TBL_PROP_SEC_COURSES
SET DEFINE OFF;
Insert into CSADMIN.TBL_PROP_SEC_COURSES (PROPID,PRI_SEQ_NUM,SEC_SEQ_NUM,INSTITUTION,CAREER,SUBJECT,CATALOG_NUM,DESCR,DESCR_TOPICS,ACAD_ORG,COURSE_STATUS,SEC_CRSE_BUDGET,MOD_BY,MOD_DATE) values (22,24,1,'UMKC','UGRD','Nut Production','1000','Nut production for dummies',null,null,null,56.78,'frielj',to_timestamp('14-APR-16 10.23.44.134000000 AM','DD-MON-RR HH.MI.SSXFF AM'));
commit;
