--------------------------------------------------------
--  DDL for Table CS_PRI_CRSE
--------------------------------------------------------

  CREATE TABLE "BBCRSSHARE"."CS_PRI_CRSE" 
   (	"INSTITUTION" VARCHAR2(5 BYTE), 
	"CRSE_ID" VARCHAR2(6 BYTE), 
	"SUBJECT" VARCHAR2(8 BYTE), 
	"CATALOG_NBR" VARCHAR2(10 BYTE), 
	"CLASS_NBR" NUMBER(38,0), 
	"CLASS_SECTION" VARCHAR2(4 BYTE), 
	"STRM" VARCHAR2(4 BYTE), 
	"DESCRSHORT" VARCHAR2(10 BYTE), 
	"LOAD_DTTM_PC" DATE, 
	"LASTUPDDTTM_PC" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BB_CRS_SHARE" ;
