--------------------------------------------------------
--  DDL for Table TBL_ACAD_ORG
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_ACAD_ORG" 
   (	"ACAD_ORG" VARCHAR2(10 BYTE), 
	"EFFDT" DATE, 
	"EFF_STATUS" VARCHAR2(1 BYTE), 
	"DESCR" VARCHAR2(30 BYTE), 
	"DESCRSHORT" VARCHAR2(10 BYTE), 
	"DESCRFORMAL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
