--------------------------------------------------------
--  DDL for Table TBL_OFFER_STATUS
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_OFFER_STATUS" 
   (	"OFFER_STATUS" VARCHAR2(20 BYTE), 
	"OFFER_DESCR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;

   COMMENT ON TABLE "CSADMIN"."TBL_OFFER_STATUS"  IS 'TBL_AWARD_STATUS: Holds the proposal award status values
VALUES: Pending, Awarded, Denied, Withdrawn, Cancelled';
