--------------------------------------------------------
--  DDL for Table TBL_LOGIN
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_LOGIN" 
   (	"USER_ID" NUMBER(*,0), 
	"SSO" VARCHAR2(20 BYTE), 
	"HASHPASS" VARCHAR2(20 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
