--------------------------------------------------------
--  DDL for Table TBL_COMMENTS
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_COMMENTS" 
   (	"COMMENT_ID" NUMBER(*,0), 
	"PROPID" NUMBER(*,0), 
	"PRI_SEQ_NUM" NUMBER(*,0), 
	"SEC_SEQ_NUM" NUMBER(*,0), 
	"COM_TEXT" CLOB, 
	"USERID" VARCHAR2(20 BYTE), 
	"COM_TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP(6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" 
 LOB ("COM_TEXT") STORE AS BASICFILE (
  TABLESPACE "COURSE_SHARE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."COMMENT_ID" IS 'Unique Identifier for comment (Primary Key)';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."PROPID" IS 'Proposal id number. Relates comment to proposal';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."PRI_SEQ_NUM" IS 'Propsal primary sequence number to relate comment if relates to a proposed primary course entry';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."SEC_SEQ_NUM" IS 'Proposal secondary sequence number to relate comment if relates to proposed secondary course entry';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."COM_TEXT" IS 'Comment text (Required)';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."USERID" IS 'User who entered the comment (Required)';
   COMMENT ON COLUMN "CSADMIN"."TBL_COMMENTS"."COM_TIMESTAMP" IS 'Timestamp as to when the comment was entered (Required, auto generated)';
