--------------------------------------------------------
--  DDL for Table TBL_PROPOSAL
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_PROPOSAL" 
   (	"PROPID" NUMBER(*,0), 
	"PROP_OFFER_TERM" VARCHAR2(4 BYTE), 
	"PROP_BUDGET_REQUESTED" NUMBER(12,2), 
	"PROP_OFFER_STATUS" VARCHAR2(5 BYTE), 
	"PROP_DESCR" CLOB, 
	"SUBMITTED_BY" VARCHAR2(20 BYTE), 
	"SUBMIT_DATE" DATE, 
	"INSERT_BY" VARCHAR2(20 BYTE), 
	"INSERT_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"MOD_BY" VARCHAR2(20 BYTE), 
	"MOD_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP(6), 
	"AWARD_TERM" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" 
 LOB ("PROP_DESCR") STORE AS BASICFILE (
  TABLESPACE "COURSE_SHARE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
