--------------------------------------------------------
--  DDL for Index SYS_MTABLE_000004F1D_IND_1
--------------------------------------------------------

  CREATE INDEX "CSADMIN"."SYS_MTABLE_000004F1D_IND_1" ON "CSADMIN"."EXPORT_JOB_SQLDEV_70" ("OBJECT_SCHEMA", "OBJECT_NAME", "OBJECT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
