--------------------------------------------------------
--  DDL for Index SYS_C007999
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSADMIN"."SYS_C007999" ON "CSADMIN"."EXPORT_JOB_SQLDEV_70" ("PROCESS_ORDER", "DUPLICATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
