--------------------------------------------------------
--  DDL for Index TBL_COURSE_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSADMIN"."TBL_COURSE_STATUS_PK" ON "CSADMIN"."TBL_COURSE_STATUS" ("COURSE_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
