--------------------------------------------------------
--  Ref Constraints for Table TBL_PROPOSAL
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" ADD CONSTRAINT "TBL_PROPOSAL_FK1" FOREIGN KEY ("PROP_OFFER_TERM")
	  REFERENCES "CSADMIN"."TBL_TERM" ("STRM") ENABLE;
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" ADD CONSTRAINT "TBL_PROPOSAL_FK2" FOREIGN KEY ("PROP_OFFER_STATUS")
	  REFERENCES "CSADMIN"."TBL_OFFER_STATUS" ("OFFER_STATUS") ENABLE;
