--------------------------------------------------------
--  DDL for Trigger TBL_PROP_SEC_COURSES_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSADMIN"."TBL_PROP_SEC_COURSES_TRG1" 
BEFORE INSERT ON TBL_PROP_SEC_COURSES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CSADMIN"."TBL_PROP_SEC_COURSES_TRG1" ENABLE;
