--------------------------------------------------------
--  DDL for Trigger TBL_PROP_SEC_COURSES_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSADMIN"."TBL_PROP_SEC_COURSES_TRG2" 
BEFORE INSERT ON TBL_PROP_SEC_COURSES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SEC_SEQ_NUM IS NULL THEN
      SELECT TBL_PROP_SEC_COURSES_SEQ1.NEXTVAL INTO :NEW.SEC_SEQ_NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CSADMIN"."TBL_PROP_SEC_COURSES_TRG2" ENABLE;
