--------------------------------------------------------
--  Constraints for Table PS_CRSE_CATALOG
--------------------------------------------------------

  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("SCC_ROW_UPD_OPRID" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("SCC_ROW_ADD_OPRID" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("SSR_DROP_CONSENT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("ENRL_UN_LD_CLC_TYP" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("COMPONENT_PRIMARY" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("FEES_EXIST" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("INSTRUCTOR_EDIT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CRSE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("RQMNT_DESIGNTN" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CRSE_CONTACT_HRS" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("LST_MULT_TRM_CRS" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("COURSE_TITLE_LONG" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("SSR_COMPONENT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("GRADE_ROSTER_PRINT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("GRADING_BASIS" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CRSE_REPEAT_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("UNITS_REPEAT_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CRSE_REPEATABLE" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("UNITS_FINAID_PROG" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("UNITS_ACAD_PROG" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("UNITS_MAXIMUM" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("UNITS_MINIMUM" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("ALLOW_MULT_ENROLL" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CONSENT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("EQUIV_CRSE_ID" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("DESCR" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("EFF_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("EFFDT" NOT NULL ENABLE);
  ALTER TABLE "CSPRDS"."PS_CRSE_CATALOG" MODIFY ("CRSE_ID" NOT NULL ENABLE);
