--------------------------------------------------------
--  Constraints for Table TBL_OFFER_STATUS
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_OFFER_STATUS" MODIFY ("OFFER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_OFFER_STATUS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("OFFER_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
