--------------------------------------------------------
--  Constraints for Table TBL_SHARED_SEC_COURSES
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("PROPID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("PRI_COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("SEC_COURSE_ID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("INSTITUTION" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("CAREER" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("CATALOG_NUM" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("DESCR" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("LONG_DESCR" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" ADD CONSTRAINT "TBL_SHARED_SEC_COURSES_PK" PRIMARY KEY ("PROPID", "PRI_COURSE_ID", "SEC_COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_SHARED_SEC_COURSES" MODIFY ("MOD_DATE" NOT NULL ENABLE);
