--------------------------------------------------------
--  Constraints for Table TBL_USERS
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_USERS" ADD CONSTRAINT "TBL_USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
