--------------------------------------------------------
--  Constraints for Table TBL_PROP_FACULTY
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_PROP_FACULTY" MODIFY ("PROPID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROP_FACULTY" MODIFY ("CRSE_SEQ_NUM" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROP_FACULTY" MODIFY ("COURSE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROP_FACULTY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROP_FACULTY" ADD CONSTRAINT "TBL_PROP_FACULTY_PK" PRIMARY KEY ("PROPID", "CRSE_SEQ_NUM", "COURSE_TYPE", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
