--------------------------------------------------------
--  Constraints for Table TBL_TERM
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_TERM" MODIFY ("STRM" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_TERM" MODIFY ("DESCR" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_TERM" MODIFY ("DESCRSHORT" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_TERM" ADD CONSTRAINT "TBL_TERM_PK" PRIMARY KEY ("STRM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
