--------------------------------------------------------
--  Constraints for Table TBL_ACAD_ORG
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" MODIFY ("ACAD_ORG" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" MODIFY ("EFF_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" MODIFY ("DESCR" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" MODIFY ("DESCRSHORT" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" MODIFY ("DESCRFORMAL" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_ACAD_ORG" ADD CONSTRAINT "TBL_ACAD_ORG_PK" PRIMARY KEY ("ACAD_ORG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
