--------------------------------------------------------
--  Constraints for Table TBL_COMMENTS
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_COMMENTS" ADD CONSTRAINT "TBL_COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_COMMENTS" MODIFY ("COM_TEXT" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_COMMENTS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_COMMENTS" MODIFY ("COM_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_COMMENTS" MODIFY ("PROPID" NOT NULL ENABLE);
