--------------------------------------------------------
--  Constraints for Table TBL_PROPOSAL
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("PROPID" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" ADD CONSTRAINT "TBL_PROPOSAL_PK" PRIMARY KEY ("PROPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("PROP_OFFER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("SUBMITTED_BY" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("SUBMIT_DATE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("INSERT_BY" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("INSERT_DATE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("MOD_BY" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_PROPOSAL" MODIFY ("MOD_DATE" NOT NULL ENABLE);
