--------------------------------------------------------
--  Constraints for Table TBL_FACULTY_TYPE
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_FACULTY_TYPE" MODIFY ("FACULTY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_FACULTY_TYPE" ADD CONSTRAINT "TBL_FACULTY_TYPE_PK" PRIMARY KEY ("FACULTY_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
