--------------------------------------------------------
--  Constraints for Table TBL_LOGIN
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" ADD CONSTRAINT "TBL_LOGIN_PK" PRIMARY KEY ("SSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("HASHPASS" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("SSO" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" ADD CONSTRAINT "TBL_LOGIN_UK1" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("USER_ID" NOT NULL ENABLE);
