--------------------------------------------------------
--  File created - Thursday-April-14-2016   
--------------------------------------------------------
@C:\wamp\www\courseshare\sql\DROPS\DROP.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\PROPOSAL_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_COMMENTS_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_LOGIN_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROPOSAL_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROPOSAL_SEQ1.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROPOSAL_SEQ2.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROPOSAL_SEQ3.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROP_PRI_COURSES_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROP_PRI_COURSES_SEQ1.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROP_PRI_COURSES_SEQ2.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROP_SEC_COURSES_SEQ.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TBL_PROP_SEC_COURSES_SEQ1.sql
@C:\wamp\www\courseshare\sql\SEQUENCES\TEST_SEQ.sql
/*@C:\wamp\www\courseshare\sql\TABLES\EXPORT_JOB_SQLDEV_70.sql*/
@C:\wamp\www\courseshare\sql\TABLES\TBL_ACAD_ORG.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_CAREER.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_COMMENTS.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_COURSE_STATUS.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_FACULTY_TYPE.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_INSTITUTION.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_LOGIN.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_OFFER_STATUS.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_PROPOSAL.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_PROP_FACULTY.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_PROP_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_PROP_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_SHARED_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_SHARED_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_TERM.sql
@C:\wamp\www\courseshare\sql\TABLES\TBL_USERS.sql
@C:\wamp\www\courseshare\sql\TABLES\CRS_XREF.sql
@C:\wamp\www\courseshare\sql\TABLES\CS_PRI_CRSE.sql
@C:\wamp\www\courseshare\sql\TABLES\CS_SEC_CRSE.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_CATALOG.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_OFFER.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_CATALOG_1.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_OFFER_1.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_CATALOG_2.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_OFFER_2.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_CATALOG_3.sql
@C:\wamp\www\courseshare\sql\TABLES\PS_CRSE_OFFER_3.sql
/*@C:\wamp\www\courseshare\sql\DATA_TABLE\EXPORT_JOB_SQLDEV_70.sql*/
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_ACAD_ORG.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_CAREER.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_COMMENTS.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_COURSE_STATUS.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_FACULTY_TYPE.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_INSTITUTION.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_LOGIN.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_OFFER_STATUS.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_PROPOSAL.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_PROP_FACULTY.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_PROP_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_PROP_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_SHARED_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_SHARED_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_TERM.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\TBL_USERS.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\CRS_XREF.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\CS_PRI_CRSE.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\CS_SEC_CRSE.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_CATALOG.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_OFFER.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_CATALOG_1.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_OFFER_1.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_CATALOG_2.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_OFFER_2.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_CATALOG_3.sql
@C:\wamp\www\courseshare\sql\DATA_TABLE\PS_CRSE_OFFER_3.sql
@C:\wamp\www\courseshare\sql\INDEXES\SYS_C007999.sql
@C:\wamp\www\courseshare\sql\INDEXES\SYS_MTABLE_000004F1D_IND_1.sql
@C:\wamp\www\courseshare\sql\INDEXES\SYS_MTABLE_000004F1D_IND_2.sql
@C:\wamp\www\courseshare\sql\INDEXES\TABLE1_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_ACAD_ORG_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_CAREER_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_COMMENTS_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_COURSE_STATUS_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_FACULTY_TYPE_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_INSTITUTION_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_LOGIN_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_LOGIN_UK1.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_PROPOSAL_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_PROP_FACULTY_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_PROP_PRI_COURSES_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_PROP_SEC_COURSES_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_SHARED_PRI_COURSES_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_SHARED_SEC_COURSES_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_TERM_PK.sql
@C:\wamp\www\courseshare\sql\INDEXES\TBL_USERS_PK.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\EXPORT_JOB_SQLDEV_70.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_ACAD_ORG.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_CAREER.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_COMMENTS.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_COURSE_STATUS.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_FACULTY_TYPE.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_INSTITUTION.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_LOGIN.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_OFFER_STATUS.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_PROPOSAL.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_PROP_FACULTY.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_PROP_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_PROP_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_SHARED_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_SHARED_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_TERM.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\TBL_USERS.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_CATALOG.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_OFFER.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_CATALOG_1.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_OFFER_1.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_CATALOG_2.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_OFFER_2.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_CATALOG_3.sql
@C:\wamp\www\courseshare\sql\CONSTRAINTS\PS_CRSE_OFFER_3.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_PROPOSAL.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_PROP_FACULTY.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_PROP_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_PROP_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_SHARED_PRI_COURSES.sql
@C:\wamp\www\courseshare\sql\REF_CONSTRAINTS\TBL_SHARED_SEC_COURSES.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_COMMENTS_TRG.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_LOGIN_TRG.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROPOSAL_TRG.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROPOSAL_TRG1.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROPOSAL_TRG2.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROP_PRI_COURSES_TRG.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROP_PRI_COURSES_TRG1.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROP_SEC_COURSES_TRG.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROP_SEC_COURSES_TRG1.sql
@C:\wamp\www\courseshare\sql\TRIGGERS\TBL_PROP_SEC_COURSES_TRG2.sql
