CREATE USER "TEST" IDENTIFIED BY VALUES 'TEST'
  DEFAULT TABLESPACE "BB_CRS_SHARE"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO test;

CREATE USER "BBCRSSHARE" IDENTIFIED BY VALUES 'BBCRSSHARE'
  DEFAULT TABLESPACE "BB_CRS_SHARE"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO bbcrsshare;

CREATE USER "CSADMIN" IDENTIFIED BY VALUES 'CSADMIN'
  DEFAULT TABLESPACE "COURSE_SHARE"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO csadmin;

CREATE USER "CSPRDC" IDENTIFIED BY VALUES 'CSPRDC'
  DEFAULT TABLESPACE "CS_PRD_C"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO csprdc;

CREATE USER "CSPRDR" IDENTIFIED BY VALUES 'CSPRDR'
  DEFAULT TABLESPACE "CS_PRD_R"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO csprdr;

CREATE USER "CSPRDK" IDENTIFIED BY VALUES 'CSPRDK'
  DEFAULT TABLESPACE "CS_PRD_K"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO csprdk;

CREATE USER "CSPRDS" IDENTIFIED BY VALUES 'CSPRDS'
  DEFAULT TABLESPACE "CS_PRD_S"
  TEMPORARY TABLESPACE "TEMP";

GRANT dba TO csprds;
