--------------------------------------------------------
--  File created - Thursday-April-14-2016   
--------------------------------------------------------
DROP TABLE "CSADMIN"."TBL_LOGIN" cascade constraints;
DROP SEQUENCE "CSADMIN"."TBL_LOGIN_SEQ";
--------------------------------------------------------
--  DDL for Sequence TBL_LOGIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CSADMIN"."TBL_LOGIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_LOGIN
--------------------------------------------------------

  CREATE TABLE "CSADMIN"."TBL_LOGIN" 
   (	"USER_ID" NUMBER(*,0), 
	"SSO" VARCHAR2(20 BYTE), 
	"HASHPASS" VARCHAR2(20 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE) DEFAULT USER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
REM INSERTING into CSADMIN.TBL_LOGIN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TBL_LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSADMIN"."TBL_LOGIN_PK" ON "CSADMIN"."TBL_LOGIN" ("SSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
--------------------------------------------------------
--  DDL for Index TBL_LOGIN_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CSADMIN"."TBL_LOGIN_UK1" ON "CSADMIN"."TBL_LOGIN" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE" ;
--------------------------------------------------------
--  Constraints for Table TBL_LOGIN
--------------------------------------------------------

  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("USER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" ADD CONSTRAINT "TBL_LOGIN_PK" PRIMARY KEY ("SSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("HASHPASS" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("SSO" NOT NULL ENABLE);
  ALTER TABLE "CSADMIN"."TBL_LOGIN" ADD CONSTRAINT "TBL_LOGIN_UK1" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COURSE_SHARE"  ENABLE;
  ALTER TABLE "CSADMIN"."TBL_LOGIN" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TBL_LOGIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CSADMIN"."TBL_LOGIN_TRG" 
BEFORE INSERT ON TBL_LOGIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "CSADMIN"."TBL_LOGIN_TRG" ENABLE;
